apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  dummy1: {{ .Values.favorite.drink }}
test1:
  {{- range $key, $val := .Values.aaa }}
  {{- range $k, $v := $val }}
    {{ $k }}: {{ $v | toJson }}
  {{- end }}
  {{- end }}
test2:   
  {{- range $key, $val := .Values.eee }}
  {{- range $k, $v := $val }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}

