apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: {{ .Values.hoge.myServiceName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.hoge.myServicePort }}

